//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadastroDeClientes.WPF.ClientesServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientesServiceReference.IClientesService")]
    public interface IClientesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/GetClientes", ReplyAction="http://tempuri.org/IClientesService/GetClientesResponse")]
        CadastroDeClientes.Model.Cliente[] GetClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/GetClientes", ReplyAction="http://tempuri.org/IClientesService/GetClientesResponse")]
        System.Threading.Tasks.Task<CadastroDeClientes.Model.Cliente[]> GetClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/AddCliente", ReplyAction="http://tempuri.org/IClientesService/AddClienteResponse")]
        void AddCliente(CadastroDeClientes.Model.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/AddCliente", ReplyAction="http://tempuri.org/IClientesService/AddClienteResponse")]
        System.Threading.Tasks.Task AddClienteAsync(CadastroDeClientes.Model.Cliente cliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientesServiceChannel : global::CadastroDeClientes.WPF.ClientesServiceReference.IClientesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientesServiceClient : System.ServiceModel.ClientBase<global::CadastroDeClientes.WPF.ClientesServiceReference.IClientesService>, global::CadastroDeClientes.WPF.ClientesServiceReference.IClientesService {
        
        public ClientesServiceClient() {
        }
        
        public ClientesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CadastroDeClientes.Model.Cliente[] GetClientes() {
            return base.Channel.GetClientes();
        }
        
        public System.Threading.Tasks.Task<CadastroDeClientes.Model.Cliente[]> GetClientesAsync() {
            return base.Channel.GetClientesAsync();
        }
        
        public void AddCliente(CadastroDeClientes.Model.Cliente cliente) {
            base.Channel.AddCliente(cliente);
        }
        
        public System.Threading.Tasks.Task AddClienteAsync(CadastroDeClientes.Model.Cliente cliente) {
            return base.Channel.AddClienteAsync(cliente);
        }
    }
}
