//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 2/25/2015 11:50:28 AM
namespace WCFDataService.Client.ServiceReference1
{
    
    /// <summary>
    /// There are no comments for ClienteModelContainer in the schema.
    /// </summary>
    public partial class ClienteModelContainer : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ClienteModelContainer object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ClienteModelContainer(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("ClienteModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("WCFDataService.Client.ServiceReference1", typeName.Substring(12)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("WCFDataService.Client.ServiceReference1", global::System.StringComparison.Ordinal))
            {
                return string.Concat("ClienteModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Clientes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Cliente> Clientes
        {
            get
            {
                if ((this._Clientes == null))
                {
                    this._Clientes = base.CreateQuery<Cliente>("Clientes");
                }
                return this._Clientes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Cliente> _Clientes;
        /// <summary>
        /// There are no comments for Clientes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToClientes(Cliente cliente)
        {
            base.AddObject("Clientes", cliente);
        }
    }
    /// <summary>
    /// There are no comments for ClienteModel.Cliente in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Clientes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Cliente : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Cliente object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="nome">Initial value of Nome.</param>
        /// <param name="sobrenome">Initial value of Sobrenome.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Cliente CreateCliente(int ID, string nome, string sobrenome)
        {
            Cliente cliente = new Cliente();
            cliente.Id = ID;
            cliente.Nome = nome;
            cliente.Sobrenome = sobrenome;
            return cliente;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Nome in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Nome
        {
            get
            {
                return this._Nome;
            }
            set
            {
                this.OnNomeChanging(value);
                this._Nome = value;
                this.OnNomeChanged();
                this.OnPropertyChanged("Nome");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Nome;
        partial void OnNomeChanging(string value);
        partial void OnNomeChanged();
        /// <summary>
        /// There are no comments for Property Sobrenome in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Sobrenome
        {
            get
            {
                return this._Sobrenome;
            }
            set
            {
                this.OnSobrenomeChanging(value);
                this._Sobrenome = value;
                this.OnSobrenomeChanged();
                this.OnPropertyChanged("Sobrenome");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Sobrenome;
        partial void OnSobrenomeChanging(string value);
        partial void OnSobrenomeChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
